exec-once = waybar
exec-once = swaync
exec-once = nm-applet --indicator
exec-once = awww-daemon
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = hypridle
exec-once = xsettingsd
exec-once = easyeffects --gapplication-service
exec-once = fcitx5 -d
exec-once = ~/.local/bin/theme-switch.sh auto
exec-once = hyprsunset
