$accent = rgb(B190FA)
$accent2 = rgb(BC5BC6)

background {
    monitor =
    path = /home/element/Pictures/wallpaper/hololive/okayu/night/background_kitty_mocha.png
    blur_passes = 3
    blur_size = 7
    contrast = 1.0
    brightness = 0.7
}

general {
    grace = 0
    hide_cursor = true
    no_fade_in = false
    disable_loading_bar = false
}

input-field {
    monitor =
    size = 350, 60
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = $accent
    inner_color = rgba(30, 30, 46, 0.6)
    font_color = rgb(CDD6F4)
    fade_on_empty = false
    placeholder_text = <i><span foreground="##B190FA">password...</span></i>
    hide_input = false
    check_color = $accent2
    fail_color = rgb(F38BA8)
    fail_text = <i>$FAIL ($ATTEMPTS)</i>
    position = 0, -50
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = $accent
    font_size = 90
    font_family = JetBrainsMono Nerd Font
    position = 0, 200
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date "+%A, %d %B"
    color = rgb(CDD6F4)
    font_size = 25
    font_family = JetBrainsMono Nerd Font
    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text = おかえり〜 🍙
    color = $accent2
    font_size = 22
    font_family = Noto Sans CJK JP
    position = 0, 30
    halign = center
    valign = center
}
