set -g tide_git_bg_color B190FA
set -g tide_git_bg_color_unstable F9E2AF
set -g tide_git_bg_color_urgent F38BA8
set -g tide_git_branch_color 1E1E2E
set -g tide_git_color_branch 1E1E2E
set -g tide_git_color_conflicted 1E1E2E
set -g tide_git_color_dirty 1E1E2E
set -g tide_git_color_operation 1E1E2E
set -g tide_git_color_staged 1E1E2E
set -g tide_git_color_stash 1E1E2E
set -g tide_git_color_untracked 1E1E2E
set -g tide_git_color_upstream 1E1E2E
set -g tide_git_conflicted_color 1E1E2E
set -g tide_git_dirty_color 1E1E2E
set -g tide_git_icon 
set -g tide_git_operation_color 1E1E2E
set -g tide_git_staged_color 1E1E2E
set -g tide_git_stash_color 1E1E2E
set -g tide_git_untracked_color 1E1E2E
set -g tide_git_upstream_color 1E1E2E
set -g tide_pwd_bg_color BC5BC6
