set -g tide_git_bg_color B190FA
set -g tide_git_bg_color_unstable DF8E1D
set -g tide_git_bg_color_urgent D20F39
set -g tide_git_branch_color 4C4F69
set -g tide_git_color_branch 4C4F69
set -g tide_git_color_conflicted 4C4F69
set -g tide_git_color_dirty 4C4F69
set -g tide_git_color_operation 4C4F69
set -g tide_git_color_staged 4C4F69
set -g tide_git_color_stash 4C4F69
set -g tide_git_color_untracked 4C4F69
set -g tide_git_color_upstream 4C4F69
set -g tide_git_conflicted_color 4C4F69
set -g tide_git_dirty_color 4C4F69
set -g tide_git_icon 
set -g tide_git_operation_color 4C4F69
set -g tide_git_staged_color 4C4F69
set -g tide_git_stash_color 4C4F69
set -g tide_git_untracked_color 4C4F69
set -g tide_git_upstream_color 4C4F69
set -g tide_pwd_bg_color BC5BC6
