set -g pane-active-border-style "fg=#B190FA"
set -g status-left  "#[fg=#4C4F69,bg=#B190FA,bold] #S #[fg=#B190FA,bg=#E6E9EF,nobold]"
set -g status-right "#[fg=#BCC0CC,bg=#E6E9EF]#[fg=#4C4F69,bg=#BCC0CC] %H:%M #[fg=#BC5BC6,bg=#BCC0CC]#[fg=#4C4F69,bg=#BC5BC6,bold] #h "
set -g window-status-current-format "#[fg=#E6E9EF,bg=#BCC0CC]#[fg=#B190FA,bg=#BCC0CC,bold] #I #W #[fg=#BCC0CC,bg=#E6E9EF]"
set -g message-style         "fg=#B190FA,bg=#BCC0CC"
set -g message-command-style "fg=#B190FA,bg=#BCC0CC"
set -g mode-style            "fg=#B190FA,bg=#BCC0CC"
set -g clock-mode-colour     "#B190FA"
