general {
    gaps_in = 6
    gaps_out = 14
    border_size = 3
    col.active_border = rgba(8839efee) rgba(ea76cbee) rgba(8839EFee) rgba(209FB5ee) rgba(8839efee) 45deg
    col.inactive_border = rgba(BCC0CCaa)
    layout = dwindle
    resize_on_border = true
    hover_icon_on_border = true
}

decoration {
    rounding = 16
    active_opacity = 1.0
    inactive_opacity = 0.96
    blur {
        enabled = true
        size = 10
        passes = 4
        new_optimizations = true
        ignore_opacity = true
        contrast = 1.0
        brightness = 1.05
        vibrancy = 0.15
        special = true
        popups = true
        popups_ignorealpha = 0.2
    }
    shadow {
        enabled = true
        range = 22
        render_power = 4
        sharp = false
        color = rgba(4C4F6955)
        color_inactive = rgba(4C4F6933)
    }
    dim_inactive = true
    dim_strength = 0.10
    dim_special = 0.4
}

animations {
    enabled = true
    bezier = oshiPop,    0.05, 0.9,  0.1,  1.08
    bezier = oshiSmooth, 0.25, 1.0,  0.5,  1.0
    bezier = oshiSpring, 0.34, 1.56, 0.64, 1.0
    bezier = oshiQuick,  0.4,  0.0,  0.2,  1.0
    bezier = oshiBounce, 0.5,  -0.4, 0.4,  1.4
    bezier = oshiOver,   0.16, 1.0,  0.3,  1.2

    animation = windows,        1, 8, oshiSpring,  popin 60%
    animation = windowsIn,      1, 8, oshiOver,    popin 50%
    animation = windowsOut,     1, 7, oshiQuick,   popin 80%
    animation = windowsMove,    1, 7, oshiSmooth

    animation = border,         1, 15, oshiSmooth
    animation = borderangle,    1, 150, oshiSmooth, loop
    animation = fade,           1, 8,  oshiQuick
    animation = fadeIn,         1, 8,  oshiOver
    animation = fadeOut,        1, 7,  oshiQuick
    animation = fadeSwitch,     1, 7,  oshiSmooth

    animation = workspaces,        1, 8, oshiPop,    slidefade 25%
    animation = workspacesIn,      1, 9, oshiBounce, slidefade 30%
    animation = workspacesOut,     1, 7, oshiQuick,  slidefade 25%
    animation = specialWorkspace,  1, 10, oshiSpring, slidefadevert 30%
    animation = specialWorkspaceIn,  1, 10, oshiBounce, slidefadevert 35%
    animation = specialWorkspaceOut, 1, 8,  oshiQuick,  slidefadevert 30%

    animation = layers,         1, 7, oshiQuick, slide
    animation = layersIn,       1, 8, oshiOver,  slide
    animation = layersOut,      1, 6, oshiQuick, slide
}

dwindle {
    pseudotile = true
    preserve_split = true
    smart_split = false
    smart_resizing = true
}

gesture = 3, horizontal, workspace
gesture = 3, vertical, special
