set -g pane-border-style "fg=#BCC0CC"
set -g pane-active-border-style "fg=#8839ef"
set -g status-style "bg=#E6E9EF,fg=#4C4F69"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left  "#[fg=#4C4F69,bg=#8839ef,bold] #S #[fg=#8839ef,bg=#E6E9EF,nobold]"
set -g status-right "#[fg=#BCC0CC,bg=#E6E9EF]#[fg=#4C4F69,bg=#BCC0CC] %H:%M #[fg=#ea76cb,bg=#BCC0CC]#[fg=#4C4F69,bg=#ea76cb,bold] #h "
set -g window-status-format         "#[fg=#6C6F85,bg=#E6E9EF] #I #W "
set -g window-status-current-format "#[fg=#E6E9EF,bg=#BCC0CC]#[fg=#8839ef,bg=#BCC0CC,bold] #I #W #[fg=#BCC0CC,bg=#E6E9EF]"
set -g window-status-separator ""
set -g message-style         "fg=#8839ef,bg=#BCC0CC"
set -g message-command-style "fg=#8839ef,bg=#BCC0CC"
set -g mode-style            "fg=#8839ef,bg=#BCC0CC"
set -g clock-mode-colour     "#8839ef"
