set -g pane-border-style "fg=#45475A"
set -g pane-active-border-style "fg=#cba6f7"
set -g status-style "bg=#181825,fg=#CDD6F4"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left  "#[fg=#1E1E2E,bg=#cba6f7,bold] #S #[fg=#cba6f7,bg=#181825,nobold]"
set -g status-right "#[fg=#45475A,bg=#181825]#[fg=#CDD6F4,bg=#45475A] %H:%M #[fg=#f5c2e7,bg=#45475A]#[fg=#1E1E2E,bg=#f5c2e7,bold] #h "
set -g window-status-format         "#[fg=#A6ADC8,bg=#181825] #I #W "
set -g window-status-current-format "#[fg=#181825,bg=#45475A]#[fg=#cba6f7,bg=#45475A,bold] #I #W #[fg=#45475A,bg=#181825]"
set -g window-status-separator ""
set -g message-style         "fg=#cba6f7,bg=#45475A"
set -g message-command-style "fg=#cba6f7,bg=#45475A"
set -g mode-style            "fg=#cba6f7,bg=#45475A"
set -g clock-mode-colour     "#cba6f7"
